### ISSUE TITLE
Restrict available Protected Item types

### ISSUE THREAD

**Issue by rjclarkewp007** [CometBackup/comet-whmcs-module#1]
Hi

Absolutely love this module and Comet Backup! Just had to put that out there. :)

Okay, so my idea is to add another configurable option in WHMCS whereby a client will need to select the backup type. (Files and Folders, SQL, HyperV, Windows Server, Exchange Server etc)

So if we could use something like:
Protected_Item_types|Select your backup type
and you then have the option to select which type you would like to use.
This will then either create or use a pre-setup policy which will restrict the Protected Items Types.

Reason for this: Backing up a home / personal computer might cost less then backing up a Server or SQL databases. It would be nice to have the option of having different pricing for the different backup types.

**Comment by burtcampbell** [comment]
I believe you can already accomplish this by setting up different policies on your Comet server.  Then create a different product/service in WHMCS for your different user types.  In the "Module Settings" tab in WHMCS for each product, you can then select the appropriate policy that fits the particular case.

**Comment by rjclarkewp007** [comment]
Thanks Burt! I actually realized this yesterday after posting. I think that should do the trick for now. :)
