### ISSUE TITLE
Restore session

### ISSUE THREAD

**Issue by fernandobayit** [CometBackup/comet-whmcs-module#4]
It would be possible to add the option to restore directly via WHMCS, or at least add a button to automatically login to the comet center to perform the restoration. Thus centralizing the customer a single point to manage the service.

**Comment by mason-cometbackup** [comment]
Performing the restore directly by web is a bit more complicated (see [this Feature Request](https://account.cometbackup.com/feature_voting/p/downloadable-backup-archive))

But, we should certainly be able to add a button to automatically log in to the Comet Server.

To automatically log in as the end-user, the WHMCS plugin must be updated to use the [`AdminAccountSessionStartAsUser`](https://account.cometbackup.com/docs/api-reference#adminaccountsessionstartasuser-generate-a-session-key-for-an-enduser-log-in-as-enduser) API that is available in Comet Server 19.6.8 or newer.

**Comment by burtcampbell** [comment]
Mason,

Is this update for the WHMCS something we need to do manually?  I would like to enable this functionality.

**Comment by fernandobayit** [comment]
News?

**Comment by fernandobayit** [comment]
News?
